info_dict = {
    "Furniture": "furniture",
    "Equipment": "equipment",
    "Iron door": "irondoor",
    "Open balcony": "openbalcony",
    "Sunny": "sunny",
    "Euro windows": "eurowindows",
    "Balcony": "balcony",
    "Playground": "playground",
    "Tile": "tile",
    "Elevator": "elevator",
    "Roadside": "roadside",
    "Gas": "gas",
    "Water": "water",
    "Security": "securitysystem",
    "Electricity": "electricity",
    "View": "view",
    "Central heating": "centralheating",
    "Sewerage, Canalization": "sewerage",
    "Air-conditioner": "airconditioner",
    "water 24/7": "water247",
    "Hot water": "hotwater",
    "Heating": "heating",
    "Laminate flooring": "laminateflooring",
    "Parquet": "parquet",
    "Storage room": "storageroom",
    "Park": "park",
    "Parking": "parking",
    "Close to the bus station": "closetothebusstation",
    "Internet": "internet",
    "Logha": "logha",
    "Garage": "garage",
}
info_dict2 = {
    "Furniture": "furniture",
    "Close to the road": "roadside",
    "Euro windows": "eurowindows",
    "The park": "park",
    "Open balcony": "openbalcony",
    "Tile": "tile",
    "Laminat": "laminateflooring",
    "Elevator": "elevator",
    "Sunny side": "sunny",
    "Beautiful paysage": "view",
    "Close to transport stop": "closetothebusstation",
    "Technique": "equipment",
    "Playground": "playground",
    "Logha": "logha",
    "Iron door": "irondoor",
    "Signal system": "securitysystem",
    "Closed balcony": "balcony",
    "Storage room": "storageroom",
    "Garage": "garage",
    "Heating": "heating",
    "Gas": "gas",
    "Hot water": "hotwater",
    "Permanent water": "water247",
    "Internet": "internet",
    "Electricity": "electricity",
    "Drinking water": "water",
    "Air conditioning": "airconditioner",
    "Parking": "parking",
    "Parquet": "parquet",
    "sewerage": "sewerage",
    "centralheating": "centralheating",
}
